# Generated by Django 4.2.7 on 2026-02-26 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, default='Lahore', max_length=120)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=80)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('estimated_visit_minutes', models.PositiveIntegerField(default=90)),
                ('budget_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('LUXURY', 'Luxury')], db_index=True, default='LOW', max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('average_rating', models.FloatField(default=0.0)),
                ('ideal_start_hour', models.PositiveIntegerField(default=9)),
                ('ideal_end_hour', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'itineraries_place',
                'ordering': ['city', 'category', 'name'],
                'indexes': [models.Index(fields=['city', 'category'], name='itineraries_city_37f7af_idx'), models.Index(fields=['city', 'budget_level'], name='itineraries_city_f729f4_idx')],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, default='Lahore', max_length=120)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('travelers', models.PositiveIntegerField(default=1)),
                ('budget_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('LUXURY', 'Luxury')], default='MEDIUM', max_length=10)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('pace', models.CharField(choices=[('RELAXED', 'Relaxed'), ('BALANCED', 'Balanced'), ('PACKED', 'Packed')], default='BALANCED', max_length=10)),
                ('days', models.JSONField(blank=True, default=list)),
                ('saved', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itineraries_itinerary',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='itineraries_user_id_be9f8d_idx'), models.Index(fields=['user', 'city', 'start_date'], name='itineraries_user_id_4b73c4_idx')],
            },
        ),
    ]
