# Generated by Django 4.2.7 on 2026-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='excluded_place_ids',
            field=models.JSONField(blank=True, default=list, help_text='Place IDs excluded from regeneration (history)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='locked_place_ids',
            field=models.JSONField(blank=True, default=list, help_text='Place IDs locked by user (survive regeneration)'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='mood',
            field=models.CharField(blank=True, choices=[('RELAXING', 'Relaxing'), ('SPIRITUAL', 'Spiritual'), ('HISTORICAL', 'Historical'), ('FOODIE', 'Foodie'), ('FUN', 'Fun & Entertainment'), ('SHOPPING', 'Shopping'), ('NATURE', 'Nature'), ('ROMANTIC', 'Romantic'), ('FAMILY', 'Family')], default='', help_text='Primary mood for trip', max_length=12),
        ),
    ]
