# Generated by Django 4.2.7 on 2026-03-01 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('booking', 'Booking'), ('payment', 'Payment'), ('itinerary', 'Itinerary'), ('promo', 'Promotion'), ('system', 'System')], default='system', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(blank=True, default='🔔', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='authenticat_user_id_550608_idx'), models.Index(fields=['user', '-created_at'], name='authenticat_user_id_a05277_idx')],
            },
        ),
    ]
