# Generated by Django 4.2.7 on 2026-02-26 09:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelScrapeRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('dest_id', models.CharField(blank=True, max_length=32, null=True)),
                ('dest_type', models.CharField(default='city', max_length=32)),
                ('checkin', models.DateField(db_index=True)),
                ('checkout', models.DateField(db_index=True)),
                ('adults', models.PositiveIntegerField(default=2)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('source_url', models.URLField(max_length=1000)),
                ('reported_count', models.PositiveIntegerField(blank=True, null=True)),
                ('scraped_count', models.PositiveIntegerField(default=0)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED')], db_index=True, default='SUCCESS', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scraper_hotel_scrape_run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapedHotelResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_uid', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('location_area', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('distance_from_center', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=80, null=True)),
                ('room_type', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_stay_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('review_rating', models.FloatField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('booking_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='scraper.hotelscraperun')),
            ],
            options={
                'db_table': 'scraper_scraped_hotel_result',
            },
        ),
        migrations.AddIndex(
            model_name='hotelscraperun',
            index=models.Index(fields=['city', 'checkin', 'checkout'], name='scraper_hot_city_ac25ac_idx'),
        ),
        migrations.AddIndex(
            model_name='hotelscraperun',
            index=models.Index(fields=['status', 'started_at'], name='scraper_hot_status_f9e914_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedhotelresult',
            index=models.Index(fields=['run', 'hotel_uid'], name='scraper_scr_run_id_87b0bf_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedhotelresult',
            index=models.Index(fields=['run', 'name'], name='scraper_scr_run_id_065e2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scrapedhotelresult',
            unique_together={('run', 'hotel_uid')},
        ),
    ]
