# Generated by Django 4.2.7 on 2026-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedhotelresult',
            name='cancellation_policy',
            field=models.CharField(blank=True, help_text='e.g. free_cancellation, non_refundable', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='scrapedhotelresult',
            name='max_occupancy',
            field=models.PositiveIntegerField(default=2, help_text='Maximum guest capacity for the room'),
        ),
        migrations.AddField(
            model_name='scrapedhotelresult',
            name='meal_plan',
            field=models.CharField(blank=True, help_text='e.g. breakfast_included, room_only', max_length=50, null=True),
        ),
    ]
