# Generated by Django 4.2.7 on 2026-03-01 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_scrapedhotelresult_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_index=True, max_length=120)),
                ('dest_id', models.CharField(blank=True, max_length=32, null=True)),
                ('dest_type', models.CharField(default='city', max_length=32)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('adults', models.PositiveIntegerField(default=2)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=12)),
                ('hotel_count', models.PositiveIntegerField(default=0)),
                ('progress_pct', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='scraper.hotelscraperun')),
            ],
            options={
                'db_table': 'scraper_scrape_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='scraper_scr_status_fa9051_idx'), models.Index(fields=['city', 'checkin', 'checkout'], name='scraper_scr_city_381c33_idx')],
            },
        ),
    ]
