# Generated by Django 4.2.7 on 2025-11-05 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_rooms', models.IntegerField()),
                ('available_rooms', models.IntegerField()),
                ('single_bed_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('family_room_price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wifi_available', models.BooleanField(default=False)),
                ('parking_available', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'hotels_hotel',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'Single'), ('family', 'Family')], max_length=10)),
                ('rooms_booked', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='hotels.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hotels_booking',
                'ordering': ['-booking_date'],
            },
        ),
    ]
