# Generated by Django 4.2.7 on 2026-02-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Room price before tax', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Human-friendly booking reference (e.g. TRV-A5K9M)', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number (e.g. INV-20260227-001)', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_locked_until',
            field=models.DateTimeField(blank=True, help_text='Room is held until this time during payment', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Service charge (5%)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GST (16%)', max_digits=10, null=True),
        ),
    ]
