# Generated by Django 4.2.7 on 2026-03-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_booking_adults_booking_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple'), ('quad', 'Quad'), ('quint', 'Quint'), ('family', 'Family'), ('suite', 'Suite'), ('deluxe', 'Deluxe'), ('dormitory', 'Dormitory'), ('entire', 'Entire Property')], db_index=True, max_length=20),
        ),
    ]
